apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: deploymentautoscaler
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: tomee-deployment
 minReplicas: 2
 maxReplicas: 5
 metrics:
  - resource:
     name: cpu
     target:
      type: Utilization
      averageUtilization: 50
    type: Resource
  - resource:
     name: storage
     target:
      type: Utilization
      averageUtilization: 50
    type: Resource
