apiVersion: v1
kind: ReplicationController
metadata:
 name: tomee-rc
spec:
 replicas: 1
 selector:
   app: tomee
 template:
  metadata:
   name: tomee-pod
   labels:
    app: tomee
  spec:
   containers:
    - name: tomee-container
      image: tomee
      ports:
       - containerPort: 8080
