apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo-pod
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: database
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: database@123
        volumeMounts:
          - name: mongopv
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongopv
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "manual"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-pod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /pv1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopv-mongo-0
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
